[package]
name = "roll"
version = "0.1.0"
authors = ["Siobhán Sterrett <siobhan.sterrett@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lazy_static = "1.4"
rand = "0.7"
regex = "1.3"
rustyline = "6.1"
